@extends('site.layout')

@section('title', 'Home')

@section('content')

	<main>
		<section id="top">
			<div class="page-banner-container parallax-1" style="background-image: url({{ asset('/images/tc_top.png') }});" >
				<div class="banner-wrapper justify-content-start container-c" data-aos="fade-up">
                    <div class="banner bn-2">
                        <div class="banner-image" style="background-image: url({{ asset('/images/tc_i.png') }});"></div>
                        <div class="banner-name">Terms & Conditions</div>
                    </div>    
                </div>
			</div>
		</section>
		<section id="page-content">
			<div class="c-wrapper-1 b-0">
                <div class="container-c">
                    <div class="inner-block" data-aos="fade-up"> 
                        <div class="row">
                            <div class="col-12">
                                <div class="c-list-1">
                                	<div class="c-list-item" data-aos="fade-right">
                                		<div class="header"><span>Acceptance</span></div>
                                		<div class="content">
                                            <p>In order to use the website and its content, you must first agree to the following Terms and conditions. You may not use the website if you do not accept the following Terms and conditions.</p>
                                            <p>These Terms and Conditions govern the use of Soldivisa.com (<strong>Site</strong>) owned and operated by ISC Services and Consulting, address: Kesklinna district, Tallinn city, Harju county, 10117, Estonia</p>
                                            <p>You accept these Terms by actually using the Services. You understand and agree that we will treat your use of the Services as acceptance of the Terms from that point onwards.</p>
                                            <p>You may not use the Services, and may not accept the Terms, if you are under the age of eighteen (18), or you are a person barred from using or receiving the Services under the laws of the United States or Canada or any other relevant jurisdiction, including the country you are resident or from which you use or access the Services. These terms of use can be changed by us at any time in our sole discretion.</p>
                                            <p>you agree to use our services at your own risk. Our services are provided on an "as is" and "as available" basis. You agree that you have made your own determination regarding the usefulness of the service or validity. We disclaim all warranties including, but not limited to, warranties of merchantability and fitness for a particular purpose.</p>
                                            <p>You agree that you are solely responsible for, and we have no responsibility to you or any third party for, any breach of your obligations under the terms (including breach of any obligations you may have with respect to a third party service) and for the consequences (including any loss or damage which we may suffer) of any such breach.</p>
                                            <p>The company and/or its representatives shall not be liable for any loss or damage caused, directly or indirectly, by any event, act or omission beyond the control of the company.</p>
                                            <p>The services are provided "as is" and "as available", and we make no warranties of any kind, express or implied, including, but not limited to, warranties of merchantability and fitness for particular purpose. the company does not warrant that company website, servers, or e-mail communications shall be available at all times and that they are free of viruses or other harmful components. the company will not be liable for any damages of any kind arising from the usage of the company's website(s), including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</p>
                                            <p>The Client acknowledges that the Company, at its sole discretion, may grant limited access to its websites and/or servers, to third party immigration practitioners who are authorized representatives under the applicable law for the purpose of supplying Canadian immigration services for a fee.</p>
                                            <p>The grant of such access to the third party immigration practitioner&rsquo;s websites and/or servers does not establish consultant-client or attorney-client relationship between the user and the authorized representatives.</p>
                                            <p>&nbsp;</p>
                                            <p>Copyrighted Information and Copyright Agent</p>
                                            <p>Please note that the pages on the Site may contain other proprietary notices and copyright information, the terms of which must be observed and followed.</p>
                                            <p>Unless otherwise noted, all information, text, articles, data, images, Documents (as defined below), software or other materials (collectively hereinafter referred to as the "Materials") contained on any page within this Site are copyrighted by SOLIDVISA (hereinafter collectively referred to as the "Copyright Holder"). Title to copyright in the Materials will at all times remain with the Copyright Holder. You may only use, download or copy the Materials contained in the Site in accordance with the Terms and Conditions. Any permitted copies of the Materials must retain the copyright notice, and any other proprietary notices contained in such Materials.</p>
                                            <p>Unless otherwise provided in the Terms and Conditions, you may not edit, or use any content contained in the Materials in any manner that may give a false or misleading impression or statement as to the Copyright Holder, or any third party referenced in the Materials. Nothing on this Site shall be construed as conferring any license under any Copyright Holder's intellectual property rights, whether by estoppel, implication or otherwise. You agree to use the Site and the Materials and services and products on the Site or accessible via the Site only for lawful purposes. We may revoke any of the foregoing rights, as well as any access and use authorizations granted to users of the site at any time.</p>
                                            <p>Except as specifically provided in these Terms and Conditions, any reproduction, distribution, replication or retransmission of any information contained on this Site without the prior written consent of SolidVisa is strictly prohibited.</p>
                                            <p>The Content of the site may not be copied, distributed, republished, uploaded, posted, or transmitted in any way without the prior written consent of SolidVisa , or unless authorized in writing elsewhere on our site, except that you may print out a copy of the Content solely for your personal use. In doing so, you may not remove or alter, or cause to be removed or altered, any copyright, trademark, trade name, service mark, or any other proprietary notice or legend appearing on any of the Content.</p>
                                            <p>It is clarified, that every effort has been made to accurately represent the product(s) s offered through this website and their potential. Any claims made or examples given are in order to reflect and represent the potential of the products and/or services, however, should not be relied on in any way in making a decision whether or not to purchase.</p>
                                            <p>Any testimonials and examples used are exceptional results, don't apply to the average purchaser and are not intended to represent or guarantee that anyone will achieve the same or similar results. Each individual's success depends on his or her background, dedication, desire and motivation as well as other factors not always known and sometimes beyond control.</p>
                                            <p>Information, images, videos and examples displayed on this website are for educational and illustrative purposes only. There is no guarantee you will receive the Visa or permits the and you recognize that there is an inherent risk that the application will not be approved by the relevant authorities and/or government offices. By ordering the product or any related products/services, you agree to all terms listed on this website.</p>
                                            <p>Every effort has been made to accurately represent the services and/or products and their potential.</p>
                                            <p>Many factors will be important in determining your actual results and no guarantees are made that you will achieve the Visas.</p>
                                            <p>The author and publisher disclaim any warranties (express or implied), merchantability, or fitness for any particular purpose. The author and publisher shall in no event be held liable to any party for any direct, indirect, punitive, special, incidental or other consequential damages arising directly or indirectly from any use of this material, which is provided "as is", and without warranties.</p>
                                            <p>Disclaimers and Limitation on Liability.</p>
                                            <p>The contents of this site, including, without limitation, the materials, are provided "as is," and SolidVisa makes no representations or warranties, express or implied, of any kind with respect to this site or its contents. SolidVisa disclaims all representations and warranties, including, without limitation, warranties of merchantability, fitness for a particular purpose, title and non-infringement.</p>
                                            <p>SolidVisa does not represent or warrant that the information accessible via this site is accurate, complete or current. this site could contain typographical errors or technical inaccuracies. SolidVisa reserves the right to add to, change or delete its content or any part thereof without notice. any price or availability information is subject to change without notice. Additionally, this site may contain information provided by third parties, which includes, without limitation, documents and software. SolidVisa makes no representation or warranty regarding the accuracy, truth, quality, suitability or reliability of such information. SolidVisa is not responsible for any errors, omissions, or inaccuracies contained in any information provided by such third parties.</p>
                                            <p>Neither SolidVisa nor any of its members, directors, employees or other representatives will be liable for damages arising out of or in connection with the use of this site or any information, products or services contained herein, which includes, without limitation, the materials, even if advised of the possibility thereof. This is a comprehensive limitation of liability that applies to all damages of any kind, including, without limitation, indirect, special and consequential damages, loss of data, income, profit or goodwill, loss of or damage to property and claims of third parties.</p>
                                            <p>You have sole responsibility for adequate protection and backup of data and/or equipment used in connection with the site and will not make any claim against SolidVisa for lost data, re-run time, inaccurate output, work delays or lost profits resulting from the use of the materials.</p>
                                            <p>you agree to defend, indemnify and hold us harmless from and against any and all claims, losses, liability costs and expenses (including but not limited to attorney's fees) arising from your violation of this agreement or any third-party's rights, including but not limited to infringement of any copyright, violation of any proprietary right and invasion of any privacy rights. this obligation shall survive any termination of this agreement. our liability will not exceed the purchase price of the services.</p>
                                            <p>Links to third party sites.</p>
                                            <p>Any other web sites that are accessible via any link on this site are not under the control of SolidVisa SolidVisa is not responsible for the contents of any linked site or any link contained in a linked site, or any changes or updates to the information contained in such sites. SolidVisa provides the linked sites to you only as a convenience and the inclusions of any such link on the site does not imply SolidVisa endorsement of the site, the organization operating such site, nor any products or services of that organization. your linking to any off-site pages or other sites is entirely at your own risk.</p>
                                            <p>Governing law; venue for any proceedings</p>
                                            <p>Any action, proceeding, dispute, claim or controversy arising out of or relating to this site or these terms and conditions, or any SolidVisa services offered on or accessed via the site, shall (i) be governed by the laws of Estonia.</p>
                                            <p>These Terms and Conditions owned and operated by ISC Services and Consulting, address: Kesklinna district, Tallinn city, Harju county, 10117, Estonia</p>
                                            <p>Complete agreement; changes to the terms and conditions</p>
                                            <p>These terms and conditions represent the entire understanding relating to the use of the site and prevail over any prior or contemporaneous, conflicting or additional, communications. SolidVisa shall have the right to revise and modify the terms and conditions at any time by posting the revised terms and conditions on the site. Any use of the site after such posting shall be deemed to constitute acceptance of the revised terms and conditions by the user.</p>
                                            <p>Indemnification</p>
                                            <p>You agree to defend, indemnify, and hold harmless SolidVisa its officers, directors, employees, members, agents and affiliates from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from your breach of the terms and conditions. SolidVisa shall provide notice to you promptly of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit or proceeding.</p>
                                            <p>By using this website you hereby agree to indemnify, defend and hold the company and its officers, directors, employees and agents harmless from any loss, damage, liability, claim, cost, awards and expense, including but not limited to reasonable attorneys&rsquo; fees, arising out of or his or her illegal and/or wrongful doing and/or any breach of agreement. without in any way limiting the foregoing, this indemnity clause shall apply to all allegations of wrongdoing or if any of the client&rsquo;s warranties or undertakings is breached or found as false.</p>
                                            <p>The client agrees to pay the indemnified entities, promptly and for any and all claims, losses, damages, costs and expenses, including attorney's fees, incurred by the any of the indemnified entities in the enforcement of any of the provisions of the agreement, or any other contracts between company and client.</p>
                                            <p>&nbsp;</p>
                                            <p>Termination</p>
                                            <p>SolidVisa reserves the right to immediately terminate your access and use of the site, or any services, in the event of any conduct by you or through your account which SolidVisa, in its sole discretion, considers to be unacceptable, or in the event of any breach by you of the terms and conditions. without limiting the foregoing, accounts that generate excessive spam will be terminated immediately. Excessive spam is considered to be a constant flood of spam messages which may cause a lag or damage to SolidVisa 's network. also, accounts that become delinquent (overdue payments by 14-days) will be terminated. upon termination, you agree to cease all use of this site and SolidVisa services.</p>
                                            <p>Privacy</p>
                                            <p>By agreeing to this terms and conditions, you hereby consent to transfer your personal information, including your full name, date of birth, contact information, contact records etc., to our associates and/or 3'rd parties, in order to receive further information about their offerings and/or with their services and/or offerings.</p>
                                            <p>You hereby consent and specifically request from us to receive from us or by our associates or 3'rd parties, marketing communications in respect to the potential offerings by way of E-mail, post, SMS, phone, push notifications. or any of which you may unsubscribe from at any time by contacting costumer service.</p>
                                            <p>By accepting this terms and conditions, you agree to being contacted and asked to consent for your name and private details to be used for advertising and promotional purposes, including by 3'rd parties, without that being considered to any breach of law or your privacy.</p>
                                            <p>Refund policy</p>
                                            <p>The Company shall refund the Client partialy with his initial full payment, minus banking fees, but only if the Company has yet to start to process the client&rsquo;s information, otherwise, no refunds are available. The client will be entiteld for a refund only if the work on his file was not started, in any case that the work of his case has started he will not be entilted to get a refund.</p>
                                            <p>We do not guarantee any outcome and no refund shall be made in case intended outcome is not reached.</p>
                                            <p>Additionally, if the client does not pass the assessment stage, they will be refunded with the full payment of the assessment, minus banking fees.</p>
                                            <p>It is clarified that no cancellation is possible once the process started and application was filled and submitted.</p>
                                            <p>Any refunds shall be paid using only and exclusively the same payment method with which you made your payments to SolidVisa.</p>
                                            <p>&nbsp;</p>
                                            <p>&nbsp;</p>
                                            <p>&nbsp;</p>
                                            <p>&nbsp;</p>
                                            <p>&nbsp;</p>
                                            <p>Transactions, Payment Fraud and Collection</p>
                                            <p>If any problem regarding any subject occurs, including financial reimbursement, please do not hesitate to contact customer service department. In case of solving the problem unilaterally by the customer through cancellation of transaction by the bank, SolidVisa reserve the right to contact the bank and submit re-presentment letter in order to claim for the funds back. SolidVisa may, at its sole discretion, cease to provide the offered Products and/or Software to certain users or to users paying with certain credit cards.</p>
                                            <p>The client will be debited before the work on his file will start, and withinh the same day of his request for the companys work.</p>
                                            <p>SolidVisa reserves the right to perform credit checks on all users with a third party credit agencies, on the basis of the information provided to us on application or by you in any other manner. SolidVisa reserves the right to use a third party electronic payment processors and/or financial institutions to process payments made by you in connection with your use of the Offered Products and/or Software. In any case of suspected or fraudulent payment, including use of stolen credit cards, or any other fraudulent activity (including any charge-back or other reversal of a payment), SolidVisa reserves the right to block a user's account and reverse any refund made, if any.</p>
                                            <p>SolidVisa shall be entitled to inform any relevant authorities or entities (including credit reference agencies) of any payment fraud or otherwise unlawful activity, and may employ collection services to recover payments. Your credit statements will appear as &ldquo;SolidVisa"</p>
                                            <p>Cancellation</p>
                                            <p>We guarantee to give clients the confirmation email within 24 - 48 hours, so applications will be processed as soon as full payment completed. If for any reason you wish to cancel a service before your assessment/immigration file has started or your product order didn't has started already, you can do so without any penalties or charges, just using Cancel/Delete email to us in your account when logged in or by email to support@SolidVisa.com You will receive a full refund of any fees paid for this particular service and for return shipping (if prepaid). However, no refund will be given after your order has sent, or lawyers has started to review and work on your request.</p>
                                            <p>No guarantee of Visa Acceptance</p>
                                            <p>You understand that the Canadian Visa Programs are an evaluation procedure that is based on Canadian authority, and therefore there cannot be any guarantee that a visa will be granted. SolidVisa&nbsp;is not involved in any way in issuing immigration visas. Minimum eligibility requirements have been detailed and listed on&nbsp;SolidVisa&nbsp;websites. It is up to you to review the requirements and ensure that you qualify within the guidelines.&nbsp;Authorized Representatives</p>
                                		</div>
                                	</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</section>
	</main>

@endsection